# Change these first
owner: ecoweb-dot-host # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: AquaticTherapy.co.uk
    url: https://aquatictherapy.co.uk/
  - name: Ecoweb.Host
    url: https://ecoweb.host/
  - name: NeilDonnelly.ie
    url: https://neildonnelly.ie/
  - name: PaulColreavy.com
    url: https://paulcolreavy.com/  
  - name: QualitySeaVeg.ie
    url: https://qualityseaveg.ie/
  - name: RIPcounties.ie
    url: https://ripcounties.ie/
  - name: SligoWellness.com
    url: https://sligowellness.com/
  - name: The ArkCounselling.ie
    url: https://thearkcounselling.ie/
  - name: Turbike.org
    url: https://turbike.org
  - name: YourVaacineSafety.ie
    url: https://yourvaccinesafety.ie/


assignees: # Users to assign downtime issues (optional)
  - ecoweb-dot-host

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Ecoweb.host status monitor
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage:  Status monitor using **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
